# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\BanhMiBietBay\Documents\Code\Python\Intern\User_Interface\EnterDHB.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class EnterDHBClass(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(679, 251)
        Dialog.setMinimumSize(QtCore.QSize(679, 251))
        Dialog.setStyleSheet("font: 87 8pt \"Shopee Display Black\";\n"
"background-color: rgb(98, 188, 157);")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalWidget_4 = QtWidgets.QWidget(Dialog)
        self.horizontalWidget_4.setMinimumSize(QtCore.QSize(150, 0))
        self.horizontalWidget_4.setMaximumSize(QtCore.QSize(150, 16777215))
        self.horizontalWidget_4.setStyleSheet("    color: rgb(170, 0, 0);\n"
"    font: 87 11pt \"Shopee Display Black\";\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 202, 166);")
        self.horizontalWidget_4.setObjectName("horizontalWidget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.horizontalWidget_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.horizontalWidget_4)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.horizontalWidget_4)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.horizontalWidget_4)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_2 = QtWidgets.QLabel(self.horizontalWidget_4)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout.addWidget(self.horizontalWidget_4)
        self.horizontalWidget_3 = QtWidgets.QWidget(Dialog)
        self.horizontalWidget_3.setStyleSheet("    color: rgb(170, 0, 0);\n"
"    font: 87 11pt \"Shopee Display Black\";\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 202, 166);")
        self.horizontalWidget_3.setObjectName("horizontalWidget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.horizontalWidget_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.EnterDHB_NgayDH = QtWidgets.QDateEdit(self.horizontalWidget_3)
        self.EnterDHB_NgayDH.setStyleSheet("\n"
"background-color: rgb(255, 222, 215);\n"
"color: rgb(170, 0, 0);\n"
"border: 1px solid #000000;\n"
"border-radius: 10px;\n"
"")
        self.EnterDHB_NgayDH.setObjectName("EnterDHB_NgayDH")
        self.verticalLayout_2.addWidget(self.EnterDHB_NgayDH)
        self.EnterDHB_MaNV = QtWidgets.QComboBox(self.horizontalWidget_3)
        self.EnterDHB_MaNV.setStyleSheet("\n"
"background-color: rgb(255, 222, 215);\n"
"color: rgb(170, 0, 0);\n"
"border: 1px solid #000000;\n"
"border-radius: 10px;\n"
"")
        self.EnterDHB_MaNV.setObjectName("EnterDHB_MaNV")
        self.verticalLayout_2.addWidget(self.EnterDHB_MaNV)
        self.EnterDHB_MaKH = QtWidgets.QLineEdit(self.horizontalWidget_3)
        self.EnterDHB_MaKH.setStyleSheet("\n"
"background-color: rgb(255, 222, 215);\n"
"color: rgb(170, 0, 0);\n"
"border: 1px solid #000000;\n"
"border-radius: 10px;\n"
"")
        self.EnterDHB_MaKH.setObjectName("EnterDHB_MaKH")
        self.verticalLayout_2.addWidget(self.EnterDHB_MaKH)
        self.EnterDHB_Total = QtWidgets.QLineEdit(self.horizontalWidget_3)
        self.EnterDHB_Total.setStyleSheet("\n"
"background-color: rgb(255, 222, 215);\n"
"color: rgb(170, 0, 0);\n"
"border: 1px solid #000000;\n"
"border-radius: 10px;\n"
"")
        self.EnterDHB_Total.setObjectName("EnterDHB_Total")
        self.verticalLayout_2.addWidget(self.EnterDHB_Total)
        self.horizontalLayout.addWidget(self.horizontalWidget_3)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalWidget_2.setMinimumSize(QtCore.QSize(100, 0))
        self.horizontalWidget_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.horizontalWidget_2.setStyleSheet("    color: rgb(170, 0, 0);\n"
"    font: 87 11pt \"Shopee Display Black\";\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 202, 166);")
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.horizontalWidget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.EnterButtonDHB = QtWidgets.QPushButton(self.horizontalWidget_2)
        self.EnterButtonDHB.setStyleSheet("QPushButton {\n"
"    font: 81 10pt \"Shopee Display ExtBd\";\n"
"    border: 1px solid #000000;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color:  rgb(170, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.EnterButtonDHB.setObjectName("EnterButtonDHB")
        self.verticalLayout_3.addWidget(self.EnterButtonDHB)
        self.ExitButtonDHB = QtWidgets.QPushButton(self.horizontalWidget_2)
        self.ExitButtonDHB.setStyleSheet("QPushButton {\n"
"    font: 81 10pt \"Shopee Display ExtBd\";\n"
"    border: 1px solid #000000;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color:  rgb(170, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.ExitButtonDHB.setObjectName("ExitButtonDHB")
        self.verticalLayout_3.addWidget(self.ExitButtonDHB)
        self.horizontalLayout_4.addWidget(self.horizontalWidget_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Ngày đơn hàng"))
        self.label_3.setText(_translate("Dialog", "Mã nhân viên"))
        self.label_4.setText(_translate("Dialog", "Mã khách hàng"))
        self.label_2.setText(_translate("Dialog", "Tổng giá trị"))
        self.EnterButtonDHB.setText(_translate("Dialog", "Hoàn tất"))
        self.ExitButtonDHB.setText(_translate("Dialog", "Hủy"))
