# -*- coding: utf-8 -*-
import pyodbc
# Form implementation generated from reading ui file 'C:\Users\BanhMiBietBay\Documents\Code\Python\Intern\User_Interface\EnterNCC.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class EnterNCCClas(object):
    def __init__(self):
        self.Dialog = None

    def setupUi(self, Dialog):
        self.Dialog = Dialog
        Dialog.setObjectName("Dialog")
        Dialog.resize(864, 291)
        Dialog.setStyleSheet("font: 87 8pt \"Shopee Display Black\";\n"
                             "\n"
                             "background-color: rgb(98, 188, 157);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.terrrI = QtWidgets.QWidget(Dialog)
        self.terrrI.setStyleSheet("border-radius: 10px;\n"
                                  "background-color: rgb(255, 202, 166);")
        self.terrrI.setObjectName("terrrI")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.terrrI)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalWidget_2 = QtWidgets.QWidget(self.terrrI)
        self.horizontalWidget_2.setMinimumSize(QtCore.QSize(150, 0))
        self.horizontalWidget_2.setStyleSheet("    color: rgb(170, 0, 0);\n"
                                              "    font: 87 11pt \"Shopee Display Black\";\n"
                                              "border-radius: 10px;\n"
                                              "background-color: rgb(255, 202, 166);")
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.horizontalWidget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.horizontalWidget_2)
        self.label_5.setStyleSheet("border-radius: 10px;")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_10 = QtWidgets.QLabel(self.horizontalWidget_2)
        self.label_10.setStyleSheet("border-radius: 10px;")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.label_8 = QtWidgets.QLabel(self.horizontalWidget_2)
        self.label_8.setStyleSheet("border-radius: 10px;")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.label_7 = QtWidgets.QLabel(self.horizontalWidget_2)
        self.label_7.setStyleSheet("border-radius: 10px;")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(self.horizontalWidget_2)
        self.label_6.setStyleSheet("border-radius: 10px;")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.horizontalLayout_6.addWidget(self.horizontalWidget_2)
        self.horizontalWidget = QtWidgets.QWidget(self.terrrI)
        self.horizontalWidget.setMinimumSize(QtCore.QSize(150, 0))
        self.horizontalWidget.setStyleSheet("    color: rgb(170, 0, 0);\n"
                                            "    font: 87 11pt \"Shopee Display Black\";\n"
                                            "border-radius: 10px;\n"
                                            "background-color: rgb(255, 202, 166);")
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.horizontalWidget)
        self.verticalLayout_5.setContentsMargins(7, 0, 7, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.EnterNCC_MNCC = QtWidgets.QLineEdit(self.horizontalWidget)
        self.EnterNCC_MNCC.setMinimumSize(QtCore.QSize(0, 30))
        self.EnterNCC_MNCC.setStyleSheet("\n"
                                         "background-color: rgb(255, 222, 215);\n"
                                         "color: rgb(170, 0, 0);\n"
                                         "border: 1px solid #000000;\n"
                                         "border-radius: 10px;\n"
                                         "")
        self.EnterNCC_MNCC.setText("")
        self.EnterNCC_MNCC.setObjectName("EnterNCC_MNCC")
        self.verticalLayout_5.addWidget(self.EnterNCC_MNCC)
        self.EnterNCC_TenNCC = QtWidgets.QLineEdit(self.horizontalWidget)
        self.EnterNCC_TenNCC.setMinimumSize(QtCore.QSize(0, 30))
        self.EnterNCC_TenNCC.setStyleSheet("\n"
                                           "background-color: rgb(255, 222, 215);\n"
                                           "color: rgb(170, 0, 0);\n"
                                           "border: 1px solid #000000;\n"
                                           "border-radius: 10px;\n"
                                           "")
        self.EnterNCC_TenNCC.setText("")
        self.EnterNCC_TenNCC.setObjectName("EnterNCC_TenNCC")
        self.verticalLayout_5.addWidget(self.EnterNCC_TenNCC)
        self.EnterNCC_SDT = QtWidgets.QLineEdit(self.horizontalWidget)
        self.EnterNCC_SDT.setMinimumSize(QtCore.QSize(0, 30))
        self.EnterNCC_SDT.setStyleSheet("\n"
                                        "background-color: rgb(255, 222, 215);\n"
                                        "color: rgb(170, 0, 0);\n"
                                        "border: 1px solid #000000;\n"
                                        "border-radius: 10px;\n"
                                        "")
        self.EnterNCC_SDT.setText("")
        self.EnterNCC_SDT.setObjectName("EnterNCC_SDT")
        self.verticalLayout_5.addWidget(self.EnterNCC_SDT)
        self.EnterNCC_DiaChi = QtWidgets.QLineEdit(self.horizontalWidget)
        self.EnterNCC_DiaChi.setMinimumSize(QtCore.QSize(0, 30))
        self.EnterNCC_DiaChi.setStyleSheet("\n"
                                           "background-color: rgb(255, 222, 215);\n"
                                           "color: rgb(170, 0, 0);\n"
                                           "border: 1px solid #000000;\n"
                                           "border-radius: 10px;\n"
                                           "")
        self.EnterNCC_DiaChi.setText("")
        self.EnterNCC_DiaChi.setObjectName("EnterNCC_DiaChi")
        self.verticalLayout_5.addWidget(self.EnterNCC_DiaChi)
        self.EnterNCC_GhiChu = QtWidgets.QLineEdit(self.horizontalWidget)
        self.EnterNCC_GhiChu.setMinimumSize(QtCore.QSize(0, 30))
        self.EnterNCC_GhiChu.setStyleSheet("\n"
                                           "background-color: rgb(255, 222, 215);\n"
                                           "color: rgb(170, 0, 0);\n"
                                           "border: 1px solid #000000;\n"
                                           "border-radius: 10px;\n"
                                           "")
        self.EnterNCC_GhiChu.setText("")
        self.EnterNCC_GhiChu.setObjectName("EnterNCC_GhiChu")
        self.verticalLayout_5.addWidget(self.EnterNCC_GhiChu)
        self.horizontalLayout_6.addWidget(self.horizontalWidget)
        self.horizontalLayout.addWidget(self.terrrI)
        self.horizontalWidget1 = QtWidgets.QWidget(Dialog)
        self.horizontalWidget1.setMinimumSize(QtCore.QSize(100, 0))
        self.horizontalWidget1.setStyleSheet("    color: rgb(170, 0, 0);\n"
                                             "    font: 87 11pt \"Shopee Display Black\";\n"
                                             "border-radius: 10px;\n"
                                             "background-color: rgb(255, 202, 166);")
        self.horizontalWidget1.setObjectName("horizontalWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.horizontalWidget1)
        self.verticalLayout.setContentsMargins(0, 6, 6, 6)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.EnterButtonNCC = QtWidgets.QPushButton(self.horizontalWidget1)
        self.EnterButtonNCC.setMinimumSize(QtCore.QSize(80, 0))
        self.EnterButtonNCC.setMaximumSize(QtCore.QSize(80, 16777215))
        self.EnterButtonNCC.setStyleSheet("QPushButton {\n"
                                          "    font: 81 10pt \"Shopee Display ExtBd\";\n"
                                          "    border: 1px solid #000000;\n"
                                          "    border-radius: 10px;\n"
                                          "}\n"
                                          "\n"
                                          "QPushButton {\n"
                                          "    background-color:  rgb(170, 0, 0);\n"
                                          "    color: rgb(255, 255, 255);\n"
                                          "}\n"
                                          "QPushButton:hover {\n"
                                          "    background-color: rgb(85, 170, 255);\n"
                                          "}")
        self.EnterButtonNCC.setObjectName("EnterButtonNCC")
        self.verticalLayout.addWidget(self.EnterButtonNCC, 0, QtCore.Qt.AlignHCenter)
        self.ExitButtonNCC = QtWidgets.QPushButton(self.horizontalWidget1)
        self.ExitButtonNCC.setMinimumSize(QtCore.QSize(80, 0))
        self.ExitButtonNCC.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ExitButtonNCC.setStyleSheet("QPushButton {\n"
                                         "    font: 81 10pt \"Shopee Display ExtBd\";\n"
                                         "    border: 1px solid #000000;\n"
                                         "    border-radius: 10px;\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton {\n"
                                         "    background-color:  rgb(170, 0, 0);\n"
                                         "    color: rgb(255, 255, 255);\n"
                                         "}\n"
                                         "QPushButton:hover {\n"
                                         "    background-color: rgb(85, 170, 255);\n"
                                         "}")
        self.ExitButtonNCC.setObjectName("ExitButtonNCC")
        self.verticalLayout.addWidget(self.ExitButtonNCC, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.horizontalWidget1, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.EnterButtonNCC.clicked.connect(self.add_data_to_db)
        self.ExitButtonNCC.clicked.connect(self.close)  # Khi nhấn nút Hủy (CancelButtonDSDVT)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_5.setText(_translate("Dialog", "Mã Nhà cung cấp"))
        self.label_10.setText(_translate("Dialog", "Tên Nhà cung cấp"))
        self.label_8.setText(_translate("Dialog", "Số điện thoại"))
        self.label_7.setText(_translate("Dialog", "Địa chỉ"))
        self.label_6.setText(_translate("Dialog", "Ghi chú"))
        self.EnterNCC_MNCC.setPlaceholderText(_translate("Dialog", "Type here"))
        self.EnterNCC_TenNCC.setPlaceholderText(_translate("Dialog", "Type here"))
        self.EnterNCC_SDT.setPlaceholderText(_translate("Dialog", "Type here"))
        self.EnterNCC_DiaChi.setPlaceholderText(_translate("Dialog", "Type here"))
        self.EnterNCC_GhiChu.setPlaceholderText(_translate("Dialog", "Type here"))
        self.EnterButtonNCC.setText(_translate("Dialog", "Hoàn tất"))
        self.ExitButtonNCC.setText(_translate("Dialog", "Hủy"))

    def add_data_to_db(self):
        print("Hello")
        server = 'BANHMIBIETBAY\\SQLEXPRESS'
        database = 'Sales_Manager'
        username = 'sa'
        password = '180403'

        # Create the database connection
        conn = pyodbc.connect(
            f'DRIVER={{SQL Server}};SERVER={server};DATABASE={database};UID={username};PWD={password}')
        ten_ncc = self.EnterNCC_TenNCC.text()
        ma_ncc = self.EnterNCC_MNCC.text()
        dien_thoai = self.EnterNCC_SDT.text()
        diachi = self.EnterNCC_DiaChi.text()
        ghichu = self.EnterNCC_GhiChu.text()

        cursor = conn.cursor()

        try:
            cursor.execute("INSERT INTO Nha_Cung_Cap (MaNCC, TenNCC, DienThoai, DiaChi, GhiChu) VALUES (?, ?, ?, ?, ?)",
                           (ma_ncc, ten_ncc, dien_thoai, diachi, ghichu))
            conn.commit()
        except Exception as e:
            conn.rollback()
            # Handle the exception as needed
        finally:
            conn.close()
            self.Dialog.close()

    def close(self):
        pass
