# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\BanhMiBietBay\Documents\Code\Python\Intern\User_Interface\EnterXacNhan.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Xac_Nhan(object):

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(375, 133)
        Form.setStyleSheet("font: 87 8pt \"Shopee Display Black\";\n"
"background-color: rgb(98, 188, 157);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalWidget = QtWidgets.QWidget(Form)
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalWidget1 = QtWidgets.QWidget(self.verticalWidget)
        self.verticalWidget1.setObjectName("verticalWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalWidget1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalWidget1)
        self.label.setStyleSheet("    color: rgb(170, 0, 0);\n"
"    font: 87 11pt \"Shopee Display Black\";\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 202, 166);")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.verticalWidget1)
        self.verticalWidget_2 = QtWidgets.QWidget(self.verticalWidget)
        self.verticalWidget_2.setStyleSheet("    color: rgb(170, 0, 0);\n"
"    font: 87 11pt \"Shopee Display Black\";\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 202, 166);")
        self.verticalWidget_2.setObjectName("verticalWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.verticalWidget_2)
        self.horizontalLayout_2.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.XacNhanXoa = QtWidgets.QPushButton(self.verticalWidget_2)
        self.XacNhanXoa.setStyleSheet("QPushButton {\n"
"    font: 81 10pt \"Shopee Display ExtBd\";\n"
"    border: 1px solid #000000;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color:  rgb(170, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.XacNhanXoa.setObjectName("XacNhanXoa")
        self.horizontalLayout_2.addWidget(self.XacNhanXoa)
        self.XacNhanHuy = QtWidgets.QPushButton(self.verticalWidget_2)
        self.XacNhanHuy.setStyleSheet("QPushButton {\n"
"    font: 81 10pt \"Shopee Display ExtBd\";\n"
"    border: 1px solid #000000;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color:  rgb(170, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.XacNhanHuy.setObjectName("XacNhanHuy")
        self.horizontalLayout_2.addWidget(self.XacNhanHuy)
        self.verticalLayout.addWidget(self.verticalWidget_2)
        self.horizontalLayout.addWidget(self.verticalWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "                             Xác nhận xóa?"))
        self.XacNhanXoa.setText(_translate("Form", "Xóa"))
        self.XacNhanHuy.setText(_translate("Form", "Hủy"))
