# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\BanhMiBietBay\Documents\Code\Python\Intern\User_Interface\EnterBG.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class EnterBGCLass(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(822, 412)
        Dialog.setMinimumSize(QtCore.QSize(822, 412))
        Dialog.setMaximumSize(QtCore.QSize(822, 412))
        Dialog.setStyleSheet("\n"
"\n"
"background-color: rgb(98, 188, 157);\n"
"font: 87 10pt \"Shopee Display Black\";\n"
"\n"
"\n"
"background-color: rgb(98, 188, 157);")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalWidget_2.setMinimumSize(QtCore.QSize(150, 0))
        self.horizontalWidget_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.horizontalWidget_2.setStyleSheet("    color: rgb(170, 0, 0);\n"
"    font: 87 11pt \"Shopee Display Black\";\n"
"    background-color: rgb(255, 175, 135);\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 202, 166);")
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.horizontalWidget_2)
        self.verticalLayout.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.horizontalWidget_2)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.horizontalWidget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.horizontalWidget_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.horizontalWidget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(self.horizontalWidget_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.horizontalWidget_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_2 = QtWidgets.QLabel(self.horizontalWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout.addWidget(self.horizontalWidget_2)
        self.horizontalWidget_3 = QtWidgets.QWidget(Dialog)
        self.horizontalWidget_3.setStyleSheet("    color: rgb(170, 0, 0);\n"
"    font: 87 11pt \"Shopee Display Black\";\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 202, 166);")
        self.horizontalWidget_3.setObjectName("horizontalWidget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.horizontalWidget_3)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.EnterBG_MBG = QtWidgets.QLineEdit(self.horizontalWidget_3)
        self.EnterBG_MBG.setMinimumSize(QtCore.QSize(0, 30))
        self.EnterBG_MBG.setStyleSheet("\n"
"background-color: rgb(255, 222, 215);\n"
"color: rgb(170, 0, 0);\n"
"border: 1px solid #000000;\n"
"border-radius: 10px;\n"
"")
        self.EnterBG_MBG.setText("")
        self.EnterBG_MBG.setObjectName("EnterBG_MBG")
        self.verticalLayout_2.addWidget(self.EnterBG_MBG)
        self.EnterBG_MaHang = QtWidgets.QLineEdit(self.horizontalWidget_3)
        self.EnterBG_MaHang.setMinimumSize(QtCore.QSize(0, 30))
        self.EnterBG_MaHang.setStyleSheet("\n"
"background-color: rgb(255, 222, 215);\n"
"color: rgb(170, 0, 0);\n"
"border: 1px solid #000000;\n"
"border-radius: 10px;\n"
"")
        self.EnterBG_MaHang.setText("")
        self.EnterBG_MaHang.setObjectName("EnterBG_MaHang")
        self.verticalLayout_2.addWidget(self.EnterBG_MaHang)
        self.EnterBG_MaDVT = QtWidgets.QLineEdit(self.horizontalWidget_3)
        self.EnterBG_MaDVT.setMinimumSize(QtCore.QSize(0, 30))
        self.EnterBG_MaDVT.setStyleSheet("\n"
"background-color: rgb(255, 222, 215);\n"
"color: rgb(170, 0, 0);\n"
"border: 1px solid #000000;\n"
"border-radius: 10px;\n"
"")
        self.EnterBG_MaDVT.setText("")
        self.EnterBG_MaDVT.setObjectName("EnterBG_MaDVT")
        self.verticalLayout_2.addWidget(self.EnterBG_MaDVT)
        self.EnterBG_SoLuong = QtWidgets.QLineEdit(self.horizontalWidget_3)
        self.EnterBG_SoLuong.setMinimumSize(QtCore.QSize(0, 30))
        self.EnterBG_SoLuong.setStyleSheet("\n"
"background-color: rgb(255, 222, 215);\n"
"color: rgb(170, 0, 0);\n"
"border: 1px solid #000000;\n"
"border-radius: 10px;\n"
"")
        self.EnterBG_SoLuong.setText("")
        self.EnterBG_SoLuong.setObjectName("EnterBG_SoLuong")
        self.verticalLayout_2.addWidget(self.EnterBG_SoLuong)
        self.EnterBG_GiaMua = QtWidgets.QLineEdit(self.horizontalWidget_3)
        self.EnterBG_GiaMua.setMinimumSize(QtCore.QSize(0, 30))
        self.EnterBG_GiaMua.setStyleSheet("\n"
"background-color: rgb(255, 222, 215);\n"
"color: rgb(170, 0, 0);\n"
"border: 1px solid #000000;\n"
"border-radius: 10px;\n"
"")
        self.EnterBG_GiaMua.setText("")
        self.EnterBG_GiaMua.setObjectName("EnterBG_GiaMua")
        self.verticalLayout_2.addWidget(self.EnterBG_GiaMua)
        self.EnterBG_GiaBan = QtWidgets.QLineEdit(self.horizontalWidget_3)
        self.EnterBG_GiaBan.setMinimumSize(QtCore.QSize(0, 30))
        self.EnterBG_GiaBan.setStyleSheet("\n"
"background-color: rgb(255, 222, 215);\n"
"color: rgb(170, 0, 0);\n"
"border: 1px solid #000000;\n"
"border-radius: 10px;\n"
"")
        self.EnterBG_GiaBan.setText("")
        self.EnterBG_GiaBan.setObjectName("EnterBG_GiaBan")
        self.verticalLayout_2.addWidget(self.EnterBG_GiaBan)
        self.EnterBG_TrangThai = QtWidgets.QComboBox(self.horizontalWidget_3)
        self.EnterBG_TrangThai.setStyleSheet("\n"
"background-color: rgb(255, 222, 215);\n"
"color: rgb(170, 0, 0);\n"
"border: 1px solid #000000;\n"
"border-radius: 10px;\n"
"")
        self.EnterBG_TrangThai.setObjectName("EnterBG_TrangThai")
        self.EnterBG_TrangThai.addItem("")
        self.EnterBG_TrangThai.addItem("")
        self.verticalLayout_2.addWidget(self.EnterBG_TrangThai)
        self.horizontalLayout.addWidget(self.horizontalWidget_3)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalWidget_21 = QtWidgets.QWidget(Dialog)
        self.horizontalWidget_21.setMinimumSize(QtCore.QSize(100, 0))
        self.horizontalWidget_21.setStyleSheet("    color: rgb(170, 0, 0);\n"
"    font: 87 11pt \"Shopee Display Black\";\n"
"    background-color: rgb(255, 175, 135);\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 202, 166);")
        self.horizontalWidget_21.setObjectName("horizontalWidget_21")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.horizontalWidget_21)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.EnterButtonBG = QtWidgets.QPushButton(self.horizontalWidget_21)
        self.EnterButtonBG.setStyleSheet("QPushButton {\n"
"    font: 81 10pt \"Shopee Display ExtBd\";\n"
"    border: 1px solid #000000;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color:  rgb(170, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.EnterButtonBG.setObjectName("EnterButtonBG")
        self.verticalLayout_3.addWidget(self.EnterButtonBG)
        self.ExitButtonBG = QtWidgets.QPushButton(self.horizontalWidget_21)
        self.ExitButtonBG.setStyleSheet("QPushButton {\n"
"    font: 81 10pt \"Shopee Display ExtBd\";\n"
"    border: 1px solid #000000;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color:  rgb(170, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.ExitButtonBG.setObjectName("ExitButtonBG")
        self.verticalLayout_3.addWidget(self.ExitButtonBG)
        self.horizontalLayout_2.addWidget(self.horizontalWidget_21)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Mã bảng giá"))
        self.label_3.setText(_translate("Dialog", "Mã hàng"))
        self.label_5.setText(_translate("Dialog", "Mã đơn vị tính"))
        self.label_4.setText(_translate("Dialog", "Số lượng"))
        self.label_6.setText(_translate("Dialog", "Giá nhập"))
        self.label_7.setText(_translate("Dialog", "Giá bán"))
        self.label_2.setText(_translate("Dialog", "Trạng thái"))
        self.EnterBG_MBG.setPlaceholderText(_translate("Dialog", "Type here"))
        self.EnterBG_MaHang.setPlaceholderText(_translate("Dialog", "Type here"))
        self.EnterBG_MaDVT.setPlaceholderText(_translate("Dialog", "Type here"))
        self.EnterBG_SoLuong.setPlaceholderText(_translate("Dialog", "Type here"))
        self.EnterBG_GiaMua.setPlaceholderText(_translate("Dialog", "Type here"))
        self.EnterBG_GiaBan.setPlaceholderText(_translate("Dialog", "Type here"))
        self.EnterBG_TrangThai.setItemText(0, _translate("Dialog", "Hoạt động"))
        self.EnterBG_TrangThai.setItemText(1, _translate("Dialog", "Không hoạt động"))
        self.EnterButtonBG.setText(_translate("Dialog", "Hoàn tất"))
        self.ExitButtonBG.setText(_translate("Dialog", "Hủy"))
