# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\BanhMiBietBay\Documents\Code\Python\Intern\Design\EnterDVT.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(498, 171)
        Dialog.setStyleSheet("background-color: rgb(45, 45, 45);\n"
"font: 87 8pt \"Shopee Display Black\";")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Add_DVT = QtWidgets.QWidget(Dialog)
        self.Add_DVT.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.Add_DVT.setObjectName("Add_DVT")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Add_DVT)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalWidget_4 = QtWidgets.QWidget(self.Add_DVT)
        self.verticalWidget_4.setMinimumSize(QtCore.QSize(150, 0))
        self.verticalWidget_4.setObjectName("verticalWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalWidget_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalWidget_4)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.verticalWidget_4)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.verticalWidget_4)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.verticalWidget_4)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout_2.addWidget(self.verticalWidget_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.Add_DVT)
        self.lineEdit_11.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_11.setStyleSheet("background-color: rgb(33, 37, 43);\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_11.setText("")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.verticalLayout_3.addWidget(self.lineEdit_11)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.Add_DVT)
        self.lineEdit_12.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_12.setStyleSheet("background-color: rgb(33, 37, 43);\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_12.setText("")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.verticalLayout_3.addWidget(self.lineEdit_12)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.Add_DVT)
        self.lineEdit_9.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_9.setStyleSheet("background-color: rgb(33, 37, 43);\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_3.addWidget(self.lineEdit_9)
        self.comboBox = QtWidgets.QComboBox(self.Add_DVT)
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.Add_DVT)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalWidget = QtWidgets.QWidget(Dialog)
        self.horizontalWidget.setMinimumSize(QtCore.QSize(100, 0))
        self.horizontalWidget.setStyleSheet("QPushButton {\n"
"    background-color: rgb(52, 59, 72);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.horizontalWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.horizontalWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.horizontalLayout.addWidget(self.horizontalWidget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "Nhập mã đơn vị tính"))
        self.label_3.setText(_translate("Dialog", "Nhập tên đơn vị tính"))
        self.label_2.setText(_translate("Dialog", "Ghi chú"))
        self.label.setText(_translate("Dialog", "Trạng thái"))
        self.lineEdit_11.setPlaceholderText(_translate("Dialog", "Type here"))
        self.lineEdit_12.setPlaceholderText(_translate("Dialog", "Type here"))
        self.lineEdit_9.setPlaceholderText(_translate("Dialog", "Type here"))
        self.comboBox.setItemText(0, _translate("Dialog", "Đang trong trạng thái sử dụng"))
        self.comboBox.setItemText(1, _translate("Dialog", "Không trong trạng thá"))
        self.pushButton.setText(_translate("Dialog", "PushButton"))
        self.pushButton_2.setText(_translate("Dialog", "PushButton"))
