# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\BanhMiBietBay\Documents\Code\Python\Intern\Design\ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 500)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 500))
        MainWindow.setStyleSheet("background-color: rgb(45, 45, 45);\n"
                                 "font: 87 8pt \"Shopee Display Black\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Bar = QtWidgets.QFrame(self.centralwidget)
        self.Top_Bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Top_Bar.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.Top_Bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Top_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_Bar.setObjectName("Top_Bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Top_Bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toggle = QtWidgets.QFrame(self.Top_Bar)
        self.frame_toggle.setMaximumSize(QtCore.QSize(70, 40))
        self.frame_toggle.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_toggle)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Btn_Toggle = QtWidgets.QPushButton(self.frame_toggle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_Toggle.sizePolicy().hasHeightForWidth())
        self.Btn_Toggle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Shopee Display Black")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.Btn_Toggle.setFont(font)
        self.Btn_Toggle.setStyleSheet("color: rgb(255, 255, 255);\n"
                                      "border: 0px solid;")
        self.Btn_Toggle.setObjectName("Btn_Toggle")
        self.verticalLayout_2.addWidget(self.Btn_Toggle)
        self.horizontalLayout.addWidget(self.frame_toggle)
        self.frame_top = QtWidgets.QFrame(self.Top_Bar)
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.rightButtons = QtWidgets.QFrame(self.frame_top)
        self.rightButtons.setGeometry(QtCore.QRect(800, 0, 127, 50))
        self.rightButtons.setMinimumSize(QtCore.QSize(0, 28))
        self.rightButtons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rightButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightButtons.setObjectName("rightButtons")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.rightButtons)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.minimizeAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.minimizeAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.minimizeAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.minimizeAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimizeAppBtn.setStyleSheet("background-color: rgb(71, 129, 255);")
        self.minimizeAppBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/icons/icon_minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeAppBtn.setIcon(icon)
        self.minimizeAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.minimizeAppBtn.setObjectName("minimizeAppBtn")
        self.horizontalLayout_6.addWidget(self.minimizeAppBtn)
        self.maximizeRestoreAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.maximizeRestoreAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.maximizeRestoreAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        font = QtGui.QFont()
        font.setFamily("Shopee Display Black")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.maximizeRestoreAppBtn.setFont(font)
        self.maximizeRestoreAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.maximizeRestoreAppBtn.setStyleSheet("background-color: rgb(71, 129, 255);")
        self.maximizeRestoreAppBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/icons/icon_maximize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maximizeRestoreAppBtn.setIcon(icon1)
        self.maximizeRestoreAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.maximizeRestoreAppBtn.setObjectName("maximizeRestoreAppBtn")
        self.horizontalLayout_6.addWidget(self.maximizeRestoreAppBtn)
        self.closeAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.closeAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.closeAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.closeAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeAppBtn.setStyleSheet("background-color: rgb(71, 129, 255);")
        self.closeAppBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/icons/icon_close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeAppBtn.setIcon(icon2)
        self.closeAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.closeAppBtn.setObjectName("closeAppBtn")
        self.horizontalLayout_6.addWidget(self.closeAppBtn)
        self.label_3 = QtWidgets.QLabel(self.frame_top)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 671, 21))
        font = QtGui.QFont()
        font.setFamily("Shopee Display Black")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.frame_top)
        self.verticalLayout.addWidget(self.Top_Bar)
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.Content)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_top_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_page_1 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_1.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Shopee Display Black")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.btn_page_1.setFont(font)
        self.btn_page_1.setStyleSheet("QPushButton {\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    background-color: rgb(35, 35, 35);\n"
                                      "    border: 0px solid;\n"
                                      "}\n"
                                      "QPushButton:hover {\n"
                                      "    background-color: rgb(85, 170, 255);\n"
                                      "}")
        self.btn_page_1.setObjectName("btn_page_1")
        self.verticalLayout_4.addWidget(self.btn_page_1)
        self.btn_page_2 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Shopee Display Black")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.btn_page_2.setFont(font)
        self.btn_page_2.setStyleSheet("QPushButton {\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    background-color: rgb(35, 35, 35);\n"
                                      "    border: 0px solid;\n"
                                      "}\n"
                                      "QPushButton:hover {\n"
                                      "    background-color: rgb(85, 170, 255);\n"
                                      "}")
        self.btn_page_2.setObjectName("btn_page_2")
        self.verticalLayout_4.addWidget(self.btn_page_2)
        self.btn_page_3 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_3.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Shopee Display Black")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.btn_page_3.setFont(font)
        self.btn_page_3.setStyleSheet("QPushButton {\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    background-color: rgb(35, 35, 35);\n"
                                      "    border: 0px solid;\n"
                                      "}\n"
                                      "QPushButton:hover {\n"
                                      "    background-color: rgb(85, 170, 255);\n"
                                      "}")
        self.btn_page_3.setObjectName("btn_page_3")
        self.verticalLayout_4.addWidget(self.btn_page_3)
        self.verticalLayout_3.addWidget(self.frame_top_menus, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.Content)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_pages)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.HomeTab_Table1 = QtWidgets.QWidget(self.page_1)
        self.HomeTab_Table1.setMinimumSize(QtCore.QSize(70, 0))
        self.HomeTab_Table1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.HomeTab_Table1.setSizeIncrement(QtCore.QSize(70, 0))
        self.HomeTab_Table1.setStyleSheet("background-color: rgb(85, 170, 255);\n"
                                          "")
        self.HomeTab_Table1.setObjectName("HomeTab_Table1")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.HomeTab_Table1)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.Home_9 = QtWidgets.QPushButton(self.HomeTab_Table1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Home_9.sizePolicy().hasHeightForWidth())
        self.Home_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Shopee Display Black")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.Home_9.setFont(font)
        self.Home_9.setStyleSheet("QPushButton {\n"
                                  "    color: rgb(255, 255, 255);\n"
                                  "    background-color: rgb(35, 35, 35);\n"
                                  "    border: 0px solid;\n"
                                  "}\n"
                                  "QPushButton:hover {\n"
                                  "    background-color: rgb(85, 170, 255);\n"
                                  "}")
        self.Home_9.setObjectName("Home_9")
        self.verticalLayout_14.addWidget(self.Home_9)
        self.Home_8 = QtWidgets.QPushButton(self.HomeTab_Table1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Home_8.sizePolicy().hasHeightForWidth())
        self.Home_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Shopee Display Black")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.Home_8.setFont(font)
        self.Home_8.setStyleSheet("QPushButton {\n"
                                  "    color: rgb(255, 255, 255);\n"
                                  "    background-color: rgb(35, 35, 35);\n"
                                  "    border: 0px solid;\n"
                                  "}\n"
                                  "QPushButton:hover {\n"
                                  "    background-color: rgb(85, 170, 255);\n"
                                  "}")
        self.Home_8.setObjectName("Home_8")
        self.verticalLayout_14.addWidget(self.Home_8)
        self.Home_7 = QtWidgets.QPushButton(self.HomeTab_Table1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Home_7.sizePolicy().hasHeightForWidth())
        self.Home_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Shopee Display Black")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.Home_7.setFont(font)
        self.Home_7.setStyleSheet("QPushButton {\n"
                                  "    color: rgb(255, 255, 255);\n"
                                  "    background-color: rgb(35, 35, 35);\n"
                                  "    border: 0px solid;\n"
                                  "}\n"
                                  "QPushButton:hover {\n"
                                  "    background-color: rgb(85, 170, 255);\n"
                                  "}")
        self.Home_7.setObjectName("Home_7")
        self.verticalLayout_14.addWidget(self.Home_7)
        self.Home_6 = QtWidgets.QPushButton(self.HomeTab_Table1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Home_6.sizePolicy().hasHeightForWidth())
        self.Home_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Shopee Display Black")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.Home_6.setFont(font)
        self.Home_6.setStyleSheet("QPushButton {\n"
                                  "    color: rgb(255, 255, 255);\n"
                                  "    background-color: rgb(35, 35, 35);\n"
                                  "    border: 0px solid;\n"
                                  "}\n"
                                  "QPushButton:hover {\n"
                                  "    background-color: rgb(85, 170, 255);\n"
                                  "}")
        self.Home_6.setObjectName("Home_6")
        self.verticalLayout_14.addWidget(self.Home_6)
        self.Home_5 = QtWidgets.QPushButton(self.HomeTab_Table1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Home_5.sizePolicy().hasHeightForWidth())
        self.Home_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Shopee Display Black")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.Home_5.setFont(font)
        self.Home_5.setStyleSheet("QPushButton {\n"
                                  "    color: rgb(255, 255, 255);\n"
                                  "    background-color: rgb(35, 35, 35);\n"
                                  "    border: 0px solid;\n"
                                  "}\n"
                                  "QPushButton:hover {\n"
                                  "    background-color: rgb(85, 170, 255);\n"
                                  "}")
        self.Home_5.setObjectName("Home_5")
        self.verticalLayout_14.addWidget(self.Home_5)
        self.Home_4 = QtWidgets.QPushButton(self.HomeTab_Table1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Home_4.sizePolicy().hasHeightForWidth())
        self.Home_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Shopee Display Black")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.Home_4.setFont(font)
        self.Home_4.setStyleSheet("QPushButton {\n"
                                  "    color: rgb(255, 255, 255);\n"
                                  "    background-color: rgb(35, 35, 35);\n"
                                  "    border: 0px solid;\n"
                                  "}\n"
                                  "QPushButton:hover {\n"
                                  "    background-color: rgb(85, 170, 255);\n"
                                  "}")
        self.Home_4.setObjectName("Home_4")
        self.verticalLayout_14.addWidget(self.Home_4)
        self.Home_2 = QtWidgets.QPushButton(self.HomeTab_Table1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Home_2.sizePolicy().hasHeightForWidth())
        self.Home_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Shopee Display Black")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.Home_2.setFont(font)
        self.Home_2.setStyleSheet("QPushButton {\n"
                                  "    color: rgb(255, 255, 255);\n"
                                  "    background-color: rgb(35, 35, 35);\n"
                                  "    border: 0px solid;\n"
                                  "}\n"
                                  "QPushButton:hover {\n"
                                  "    background-color: rgb(85, 170, 255);\n"
                                  "}")
        self.Home_2.setObjectName("Home_2")
        self.verticalLayout_14.addWidget(self.Home_2)
        self.horizontalLayout_5.addWidget(self.HomeTab_Table1)
        self.InforTab_Table1 = QtWidgets.QWidget(self.page_1)
        self.InforTab_Table1.setObjectName("InforTab_Table1")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.InforTab_Table1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalWidget = QtWidgets.QWidget(self.InforTab_Table1)
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalStackedWidget_2 = QtWidgets.QStackedWidget(self.verticalWidget)
        self.verticalStackedWidget_2.setObjectName("verticalStackedWidget_2")
        self.TT_DVT_Page = QtWidgets.QWidget()
        self.TT_DVT_Page.setObjectName("TT_DVT_Page")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.TT_DVT_Page)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalWidget1 = QtWidgets.QWidget(self.TT_DVT_Page)
        self.verticalWidget1.setMaximumSize(QtCore.QSize(16777215, 100))
        self.verticalWidget1.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.verticalWidget1.setObjectName("verticalWidget1")
        self.frame_div_content_1 = QtWidgets.QFrame(self.verticalWidget1)
        self.frame_div_content_1.setGeometry(QtCore.QRect(0, 0, 691, 110))
        self.frame_div_content_1.setMinimumSize(QtCore.QSize(0, 110))
        self.frame_div_content_1.setMaximumSize(QtCore.QSize(16777215, 110))
        self.frame_div_content_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_div_content_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_div_content_1.setObjectName("frame_div_content_1")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_div_content_1)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frame_title_wid_2 = QtWidgets.QFrame(self.frame_div_content_1)
        self.frame_title_wid_2.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_title_wid_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title_wid_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title_wid_2.setObjectName("frame_title_wid_2")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_title_wid_2)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.labelBoxBlenderInstalation_2 = QtWidgets.QLabel(self.frame_title_wid_2)
        font = QtGui.QFont()
        font.setFamily("Shopee Display Black")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.labelBoxBlenderInstalation_2.setFont(font)
        self.labelBoxBlenderInstalation_2.setStyleSheet("\n"
                                                        "color: rgb(255, 255, 255);")
        self.labelBoxBlenderInstalation_2.setObjectName("labelBoxBlenderInstalation_2")
        self.verticalLayout_20.addWidget(self.labelBoxBlenderInstalation_2)
        self.verticalLayout_19.addWidget(self.frame_title_wid_2)
        self.frame_content_wid_2 = QtWidgets.QFrame(self.frame_div_content_1)
        self.frame_content_wid_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_content_wid_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content_wid_2.setObjectName("frame_content_wid_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_content_wid_2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_content_wid_2)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_2.setStyleSheet("background-color: rgb(33, 37, 43);\n"
                                      "color: rgb(255, 255, 255);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 0, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_content_wid_2)
        self.pushButton_9.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Shopee Display Black")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setStyleSheet("background-color: rgb(52, 59, 72);\n"
                                        "color: rgb(255, 255, 255);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/icons/cil-folder-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon3)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_2.addWidget(self.pushButton_9, 0, 1, 1, 1)
        self.labelVersion_4 = QtWidgets.QLabel(self.frame_content_wid_2)
        self.labelVersion_4.setStyleSheet("color: rgb(113, 126, 149);")
        self.labelVersion_4.setLineWidth(1)
        self.labelVersion_4.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.labelVersion_4.setObjectName("labelVersion_4")
        self.gridLayout_2.addWidget(self.labelVersion_4, 1, 0, 1, 2)
        self.horizontalLayout_12.addLayout(self.gridLayout_2)
        self.verticalLayout_19.addWidget(self.frame_content_wid_2)
        self.verticalLayout_13.addWidget(self.verticalWidget1)
        self.verticalWidget_2 = QtWidgets.QWidget(self.TT_DVT_Page)
        self.verticalWidget_2.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.verticalWidget_2.setObjectName("verticalWidget_2")
        self.row_3 = QtWidgets.QFrame(self.verticalWidget_2)
        self.row_3.setGeometry(QtCore.QRect(0, 0, 681, 271))
        self.row_3.setMinimumSize(QtCore.QSize(0, 150))
        self.row_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.row_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.row_3.setObjectName("row_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.row_3)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.tableView = QtWidgets.QTableView(self.row_3)
        self.tableView.setStyleSheet("background-color: rgb(255, 229, 237);\n")
        self.tableView.setObjectName("tableView")
        self.horizontalLayout_13.addWidget(self.tableView)
        self.verticalLayout_13.addWidget(self.verticalWidget_2)
        self.verticalStackedWidget_2.addWidget(self.TT_DVT_Page)
        self.TT_NCC_Page = QtWidgets.QWidget()
        self.TT_NCC_Page.setObjectName("TT_NCC_Page")
        self.verticalStackedWidget_2.addWidget(self.TT_NCC_Page)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalStackedWidget_2.addWidget(self.page_4)
        self.verticalLayout_9.addWidget(self.verticalStackedWidget_2)
        self.verticalLayout_11.addWidget(self.verticalWidget)
        self.horizontalLayout_5.addWidget(self.InforTab_Table1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalFrame = QtWidgets.QFrame(self.page_2)
        self.verticalFrame.setObjectName("verticalFrame")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.verticalFrame)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalFrame_2 = QtWidgets.QFrame(self.verticalFrame)
        self.horizontalFrame_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.horizontalFrame_2.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.horizontalFrame_2.setObjectName("horizontalFrame_2")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.horizontalFrame_2)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.pushButton_7 = QtWidgets.QPushButton(self.horizontalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(35, 35, 35);\n"
                                        "    border: 0px solid;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(85, 170, 255);\n"
                                        "}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_16.addWidget(self.pushButton_7)
        self.pushButton_6 = QtWidgets.QPushButton(self.horizontalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(35, 35, 35);\n"
                                        "    border: 0px solid;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(85, 170, 255);\n"
                                        "}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_16.addWidget(self.pushButton_6)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(35, 35, 35);\n"
                                        "    border: 0px solid;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(85, 170, 255);\n"
                                        "}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_16.addWidget(self.pushButton_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(35, 35, 35);\n"
                                        "    border: 0px solid;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(85, 170, 255);\n"
                                        "}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_16.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(35, 35, 35);\n"
                                        "    border: 0px solid;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(85, 170, 255);\n"
                                        "}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_16.addWidget(self.pushButton_4)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(35, 35, 35);\n"
                                        "    border: 0px solid;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(85, 170, 255);\n"
                                        "}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_16.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.horizontalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setStyleSheet("QPushButton {\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    background-color: rgb(35, 35, 35);\n"
                                      "    border: 0px solid;\n"
                                      "}\n"
                                      "QPushButton:hover {\n"
                                      "    background-color: rgb(85, 170, 255);\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_16.addWidget(self.pushButton)
        self.horizontalLayout_11.addWidget(self.horizontalFrame_2)
        self.horizontalFrame = QtWidgets.QFrame(self.verticalFrame)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_11.addWidget(self.horizontalFrame)
        self.verticalLayout_6.addWidget(self.verticalFrame)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setFamily("Shopee Display Black")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #FFF;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_8.addWidget(self.label)
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.verticalStackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Btn_Toggle.setText(_translate("MainWindow", "Home"))
        self.minimizeAppBtn.setToolTip(_translate("MainWindow", "Minimize"))
        self.maximizeRestoreAppBtn.setToolTip(_translate("MainWindow", "Maximize"))
        self.closeAppBtn.setToolTip(_translate("MainWindow", "Close"))
        self.label_3.setText(_translate("MainWindow", "Quản lý cửa hàng tạp hóa"))
        self.btn_page_1.setText(_translate("MainWindow", "Thông tin"))
        self.btn_page_2.setText(_translate("MainWindow", "Chỉnh sửa"))
        self.btn_page_3.setText(_translate("MainWindow", "Đăng nhập"))
        self.Home_9.setText(_translate("MainWindow", "Danh sách đơn vị tính"))
        self.Home_8.setText(_translate("MainWindow", "Nhà cung cấp"))
        self.Home_7.setText(_translate("MainWindow", "Danh sách hàng hóa"))
        self.Home_6.setText(_translate("MainWindow", "Bảng giá"))
        self.Home_5.setText(_translate("MainWindow", "Đơn hàng"))
        self.Home_4.setText(_translate("MainWindow", "Chi tiết đơn hàng"))
        self.Home_2.setText(_translate("MainWindow", "Quản lý nhân viên"))
        self.labelBoxBlenderInstalation_2.setText(_translate("MainWindow", "Tìm Kiếm Đơn Vị Tính"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Type here"))
        self.pushButton_9.setText(_translate("MainWindow", "Tìm kiếm"))
        self.labelVersion_4.setText(_translate("MainWindow", "Hãy nhập mã đơn vị tính"))
        self.pushButton_7.setText(_translate("MainWindow", "Danh sách đơn vị tính"))
        self.pushButton_6.setText(_translate("MainWindow", "Nhà cung cấp"))
        self.pushButton_3.setText(_translate("MainWindow", "Danh sách hàng hóa"))
        self.pushButton_5.setText(_translate("MainWindow", "Bảng giá"))
        self.pushButton_4.setText(_translate("MainWindow", "Đơn hàng"))
        self.pushButton_2.setText(_translate("MainWindow", "Chi tiết đơn hàng"))
        self.pushButton.setText(_translate("MainWindow", "Quản lý nhân viên"))
        self.label.setText(_translate("MainWindow", "PAGE 3"))
