# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file
# 'C:\Users\nguye\Desktop\Practise_Python-main\Quanlytkbsv\Login_qltkbsv\welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def __init__(self):
        self.pushButton_2 = None
        self.label = None
        self.label_2 = None
        self.pushButton = None

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(420, 520)
        Dialog.setMinimumSize(QtCore.QSize(420, 520))
        Dialog.setMaximumSize(QtCore.QSize(420, 620))
        font = QtGui.QFont()
        font.setPointSize(28)
        Dialog.setFont(font)
        Dialog.setStyleSheet("background-color: rgb(255, 251, 248);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 110, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(38, 0, 115);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(90, 170, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 0, 88);")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(130, 220, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 270, 161, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Student\'s Timetable"))
        self.label_2.setText(_translate("Dialog", "Log in or sign up a new account"))
        self.pushButton.setText(_translate("Dialog", "Log in"))
        self.pushButton_2.setText(_translate("Dialog", "Sign up "))
