# -*- coding: utf-8 -*-
import pyodbc
# Form implementation generated from reading ui file 'C:\Users\BanhMiBietBay\Documents\Code\Python\Grocery_Store_Management_Python_And_PyQtGUI\User_Interface\Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget
from Grocery_Store_Management_Python_And_PyQtGUI.Database.Connect_Database import connect_db

class EnterLoginClass(object):

    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.resize(400, 600)
        LoginForm.setMinimumSize(QtCore.QSize(400, 600))
        LoginForm.setStyleSheet("font: 87 8pt \"Shopee Display Black\";\n"
                                "background-color: rgb(98, 188, 157);")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(LoginForm)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalWidget = QtWidgets.QWidget(LoginForm)
        self.verticalWidget.setMinimumSize(QtCore.QSize(0, 400))
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalWidget_2 = QtWidgets.QWidget(self.verticalWidget)
        self.verticalWidget_2.setStyleSheet("    color: rgb(170, 0, 0);\n"
                                            "    font: 87 11pt \"Shopee Display Black\";\n"
                                            "border-radius: 10px;\n"
                                            "background-color: rgb(255, 202, 166);")
        self.verticalWidget_2.setObjectName("verticalWidget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalWidget_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.verticalWidget_2)
        self.label_4.setStyleSheet("font: 87 29pt \"Shopee Display Black\";")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.verticalLayout_2.addWidget(self.verticalWidget_2)
        self.verticalWidget_3 = QtWidgets.QWidget(self.verticalWidget)
        self.verticalWidget_3.setObjectName("verticalWidget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalWidget_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalFrame_2 = QtWidgets.QFrame(self.verticalWidget_3)
        self.horizontalFrame_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.horizontalFrame_2.setStyleSheet("    color: rgb(170, 0, 0);\n"
                                             "    font: 87 11pt \"Shopee Display Black\";\n"
                                             "border-radius: 10px;\n"
                                             "background-color: rgb(255, 202, 166);")
        self.horizontalFrame_2.setObjectName("horizontalFrame_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.horizontalFrame_2)
        self.verticalLayout_8.setContentsMargins(10, 30, 0, 30)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.horizontalFrame_2)
        font = QtGui.QFont()
        font.setFamily("Shopee Display Black")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_8.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.horizontalFrame_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.horizontalLayout_6.addWidget(self.horizontalFrame_2)
        self.verticalFrame = QtWidgets.QFrame(self.verticalWidget_3)
        self.verticalFrame.setStyleSheet("    color: rgb(170, 0, 0);\n"
                                         "    font: 87 11pt \"Shopee Display Black\";\n"
                                         "border-radius: 10px;\n"
                                         "background-color: rgb(255, 202, 166);")
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_7.setContentsMargins(0, 40, -1, -1)
        self.verticalLayout_7.setSpacing(30)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.LineUserName = QtWidgets.QLineEdit(self.verticalFrame)
        self.LineUserName.setMinimumSize(QtCore.QSize(200, 30))
        self.LineUserName.setStyleSheet("\n"
                                        "background-color: rgb(255, 222, 215);\n"
                                        "color: rgb(170, 0, 0);\n"
                                        "border: 1px solid #000000;\n"
                                        "border-radius: 10px;\n"
                                        "")
        self.LineUserName.setText("")
        self.LineUserName.setObjectName("LineUserName")
        self.verticalLayout_7.addWidget(self.LineUserName, 0, QtCore.Qt.AlignLeft)
        self.LinePassword = QtWidgets.QLineEdit(self.verticalFrame)
        self.LinePassword.setMinimumSize(QtCore.QSize(200, 30))
        self.LinePassword.setStyleSheet("\n"
                                        "background-color: rgb(255, 222, 215);\n"
                                        "color: rgb(170, 0, 0);\n"
                                        "border: 1px solid #000000;\n"
                                        "border-radius: 10px;\n"
                                        "")
        self.LinePassword.setText("")
        self.LinePassword.setObjectName("LinePassword")
        self.verticalLayout_7.addWidget(self.LinePassword, 0, QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.horizontalLayout_6.addWidget(self.verticalFrame)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addWidget(self.verticalWidget_3)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addWidget(self.verticalWidget)
        self.verticalWidget_21 = QtWidgets.QWidget(LoginForm)
        self.verticalWidget_21.setObjectName("verticalWidget_21")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.verticalWidget_21)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalWidget = QtWidgets.QWidget(self.verticalWidget_21)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_4.addWidget(self.horizontalWidget)
        self.horizontalWidget_2 = QtWidgets.QWidget(self.verticalWidget_21)
        self.horizontalWidget_2.setMinimumSize(QtCore.QSize(200, 0))
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LoginButton = QtWidgets.QPushButton(self.horizontalWidget_2)
        self.LoginButton.setMinimumSize(QtCore.QSize(0, 40))
        self.LoginButton.setStyleSheet("QPushButton {\n"
                                       "    font: 81 10pt \"Shopee Display ExtBd\";\n"
                                       "    border: 1px solid #000000;\n"
                                       "    border-radius: 10px;\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton {\n"
                                       "    background-color:  rgb(170, 0, 0);\n"
                                       "    color: rgb(255, 255, 255);\n"
                                       "}\n"
                                       "QPushButton:hover {\n"
                                       "    background-color: rgb(85, 170, 255);\n"
                                       "}")
        self.LoginButton.setObjectName("LoginButton")
        self.horizontalLayout_2.addWidget(self.LoginButton)
        self.horizontalLayout_4.addWidget(self.horizontalWidget_2)
        self.horizontalWidget_3 = QtWidgets.QWidget(self.verticalWidget_21)
        self.horizontalWidget_3.setObjectName("horizontalWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalWidget_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.FaceIDButton = QtWidgets.QPushButton(self.horizontalWidget_3)
        self.FaceIDButton.setMaximumSize(QtCore.QSize(40, 40))
        self.FaceIDButton.setStyleSheet("QPushButton {\n"
                                        "    background-repeat: no-repeat;\n"
                                        "    background-image: url(:/newPrefix/cil-smile.png);\n"
                                        "    background-position: center;\n"
                                        "    background-size: cover;\n"
                                        "}\n"
                                        "QPushButton {\n"
                                        "    border: 1px solid #000000;\n"
                                        "    border-radius: 10px;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton {\n"
                                        "    font: 81 10pt \"Shopee Display ExtBd\";\n"
                                        "    border: 1px solid #000000;\n"
                                        "    border-radius: 10px;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton {\n"
                                        "    background-color:  rgb(170, 0, 0);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(85, 170, 255);\n"
                                        "}")
        self.FaceIDButton.setText("")
        self.FaceIDButton.setIconSize(QtCore.QSize(30, 30))
        self.FaceIDButton.setObjectName("FaceIDButton")
        self.horizontalLayout_3.addWidget(self.FaceIDButton)
        self.horizontalLayout_4.addWidget(self.horizontalWidget_3)
        self.verticalLayout_4.addWidget(self.verticalWidget_21, 0, QtCore.Qt.AlignTop)
        self.verticalWidget_31 = QtWidgets.QWidget(LoginForm)
        self.verticalWidget_31.setObjectName("verticalWidget_31")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalWidget_31)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.verticalWidget_31)
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label, 0, QtCore.Qt.AlignRight)
        self.RegisterButton = QtWidgets.QPushButton(self.widget)
        self.RegisterButton.setMaximumSize(QtCore.QSize(80, 30))
        self.RegisterButton.setStyleSheet("QPushButton {\n"
                                          "    font: 81 10pt \"Shopee Display ExtBd\";\n"
                                          "    border: 1px solid #000000;\n"
                                          "    border-radius: 10px;\n"
                                          "}\n"
                                          "\n"
                                          "QPushButton {\n"
                                          "    background-color:  rgb(170, 0, 0);\n"
                                          "    color: rgb(255, 255, 255);\n"
                                          "}\n"
                                          "QPushButton:hover {\n"
                                          "    background-color: rgb(85, 170, 255);\n"
                                          "}")
        self.RegisterButton.setObjectName("RegisterButton")
        self.horizontalLayout_5.addWidget(self.RegisterButton)
        self.verticalLayout_3.addWidget(self.widget)
        self.verticalLayout_4.addWidget(self.verticalWidget_31)

        self.retranslateUi(LoginForm)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "Form"))
        self.label_4.setText(_translate("LoginForm", "Welcome"))
        self.label_2.setText(_translate("LoginForm", "Tài khoản"))
        self.label_3.setText(_translate("LoginForm", "Mật khẩu"))
        self.LineUserName.setPlaceholderText(_translate("LoginForm", "Type here"))
        self.LinePassword.setPlaceholderText(_translate("LoginForm", "Type here"))
        self.LinePassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.LoginButton.setText(_translate("LoginForm", "Đăng nhập"))
        self.label.setText(_translate("LoginForm", "Chưa có tài khoản?"))
        self.RegisterButton.setText(_translate("LoginForm", "Đăng ký"))


